# Generated by Django 4.0.5 on 2022-09-15 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchers',
            field=models.ManyToManyField(related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
