# Generated by Django 4.0.5 on 2022-09-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listing_watchers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
